### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by toyg** [terra-farm/terraform-provider-virtualbox#99] opened 2021-03-28 09:34 UTC
```
$> go get github.com/terra-farm/terraform-provider-virtualbox
package github.com/vmihailenco/msgpack/codes: cannot find package "github.com/vmihailenco/msgpack/codes" in any of:
	/usr/local/opt/go/libexec/src/github.com/vmihailenco/msgpack/codes (from $GOROOT)
	/Users/toyg/src/Go/src/github.com/vmihailenco/msgpack/codes (from $GOPATH)
```

vmihailenco/msgpack has to be installed manually for this app to build. If this is expected, it should be mentioned in readme or documentation.

**Comment by cftang0827** [comment] 2021-04-08 12:14
I have same issue here.

**Comment by cftang0827** [comment] 2021-04-08 12:21
there's a workaround way, you can build it from source and it will be in your `$GOPATH/bin/` 
just use `make build` and it will build with no error.

**Comment by fortunella** [comment] 2021-05-22 10:56
Build runs without error - as you said. But what to do next to use the provider in terraform?

**Comment by VoyTechnology** [comment] 2021-07-01 14:55
@fortunella Since #90 you can use the version from the Terraform Registry, no need to build locally:

https://registry.terraform.io/providers/terra-farm/virtualbox/latest

I will update the README to reflect these changes.

---

I have tried to `go get` in an empty Docker container and it worked fine. I can't reproduce the issue.

**Comment by VoyTechnology** [comment] 2021-09-22 15:46
The README has been updated so you can use the latest tag instead of building from source.

I will close this issue since I was unable to reproduce it, both locally (on windows, linux or MacOS), and in CI.

**Closed** 2021-09-22 15:46 UTC
